matrix:
    BASE_IMAGE:
       - ubuntu:xenial
       - ubuntu:14.04

build:
  image: $$BASE_IMAGE
  pull: true
  environment:
    # Change the following to reflect your local preferences
    - PACKAGE=firedrake
    - FIREDRAKE_HOME=/firedrake
    - FIREDRAKE_GID=1000
    - FIREDRAKE_UID=1000
  commands: 
    # Bring the image up to date
    - apt-get -y update
    - apt-get -y dist-upgrade
    # Install dependencies for a single run of firedrake-install
    - apt-get -y install sudo python-minimal python-pip
    - pip install virtualenv
    - mkdir $FIREDRAKE_HOME
    - groupadd -g $FIREDRAKE_GID firedrake
    - useradd -d $FIREDRAKE_HOME -u $FIREDRAKE_UID -g $FIREDRAKE_GID firedrake
    # Passwordless sudo: \072 is octal for :
    # Colon breaks the drone yaml parser
    - /bin/echo -e "firedrake ALL=NOPASSWD\072 ALL\n" >> /etc/sudoers
    - cd $FIREDRAKE_HOME
    - $DRONE_BUILD_DIR/scripts/firedrake-install --disable-ssh --minimal-petsc --package-branch firedrake $DRONE_COMMIT
    - virtualenv firedrake
    - . firedrake/bin/activate
    - pip install pytest
    - chown -R firedrake.firedrake $FIREDRAKE_HOME
    # Run tests as the firedrake user, pushing in the current path.
    - sudo -EHu firedrake env PATH="$PATH" py.test -n auto -v firedrake/src/firedrake/tests/
