sudo: false
notifications:
  irc:
    channels: "chat.freenode.net#firedrake"
    skip_join: true
    on_success: change
    on_failure: always
    template: "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} | %{build_url}"
language: python
# We're not Python 2.6 compatible at the moment
python: "2.7"
addons:
  apt:
    packages:
        - build-essential
        - python-dev
        - git
        - mercurial
        - python-pip
        - libopenmpi-dev
        - openmpi-bin
        - libblas-dev
        - liblapack-dev
        - gfortran
        - libhdf5-mpi-dev
        - swig
env:
  global:
    - C_INCLUDE_PATH=/usr/lib/openmpi/include
    - PETSC_CONFIGURE_OPTIONS="--download-ctetgen --download-triangle --download-chaco"
  matrix:
    - PYOP2_BACKEND=sequential PYOP2_TESTS=regression
    - OMP_NUM_THREADS=1 PYOP2_BACKEND=openmp PYOP2_TESTS=regression
    - OMP_NUM_THREADS=2 PYOP2_BACKEND=openmp PYOP2_TESTS=regression
    - PYOP2_BACKEND=sequential PYOP2_TESTS="multigrid benchmarks"
    - OMP_NUM_THREADS=1 PYOP2_BACKEND=openmp PYOP2_TESTS="benchmarks multigrid"
    - OMP_NUM_THREADS=2 PYOP2_BACKEND=openmp PYOP2_TESTS="benchmarks multigrid"
    - PYOP2_BACKEND=sequential PYOP2_TESTS=extrusion
    - OMP_NUM_THREADS=1 PYOP2_BACKEND=openmp PYOP2_TESTS=extrusion
    - OMP_NUM_THREADS=2 PYOP2_BACKEND=openmp PYOP2_TESTS=extrusion
virtualenv:
  system_site_packages: true
# command to install dependencies
before_install:
  - wget https://raw.github.com/OP2/PyOP2/master/requirements-minimal.txt
  - pip install -U pytest
  - pip install psutil
  - pip install cachetools
  - pip install pytest-benchmark
  - "xargs -l1 pip install --allow-external mpi4py --allow-unverified mpi4py \
       --allow-external petsc --allow-unverified petsc \
       --allow-external petsc4py  --allow-unverified petsc4py \
       < requirements-minimal.txt"
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install argparse ordereddict; fi
install:
  - make
# command to run tests
script:
  - export PYTHONPATH=`pwd`:$PYTHONPATH
  - make lint
  - (rc=0; for t in ${PYOP2_TESTS}; do py.test --short -v tests/${t} || rc=$?; done; exit $rc)
