sudo: false
notifications:
  irc:
    channels: "chat.freenode.net#firedrake"
    skip_join: true
    on_success: change
    on_failure: always
    template: "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} | %{build_url}"
# language: python
language: c
# We're not Python 2.6 compatible at the moment
# python: "2.7"
addons:
  apt:
    packages:
        - build-essential
        - python-dev
        - git
        - mercurial
        - python-pip
        - libopenmpi-dev
        - openmpi-bin
        - libblas-dev
        - liblapack-dev
        - gfortran
        - libspatialindex-dev
        - gmsh
os:
    - linux
    - osx
# Separate cache directories for OSX and Linux
cache:
  directories:
    - $HOME/cached_dependencies_$TRAVIS_OS_NAME
env:
  global:
    - CC=mpicc
    # The install script expects to see this environment variable
    - CACHE_DIRECTORY=$HOME/cached_dependencies_$TRAVIS_OS_NAME
    - FIREDRAKE_TRAVIS_TESTS=1
  matrix:
    - PYOP2_BACKEND=none
matrix:
  exclude:
    - env: PYOP2_BACKEND=none
  include:
    - os: osx
      # Only test a few things on OSX until we can cache some of the
      # build dependencies, otherwise we often get timeouts.
      env: PYOP2_BACKEND=sequential PYOP2_TESTS="extrusion" TEST_ADJOINT="TRUE"
    - os: linux
      env: PYOP2_BACKEND=sequential PYOP2_TESTS=regression
    - os: linux
      env: OMP_NUM_THREADS=2 PYOP2_BACKEND=openmp PYOP2_TESTS=regression
    - os: linux
      env: PYOP2_BACKEND=sequential PYOP2_TESTS="extrusion checkpoints multigrid benchmarks demos" TEST_ADJOINT="TRUE"
    - os: linux
      env: OMP_NUM_THREADS=2 PYOP2_BACKEND=openmp PYOP2_TESTS="extrusion checkpoints multigrid benchmarks" TEST_ADJOINT="TRUE"
before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update; brew install python; brew link --overwrite python ; fi
  - pip install -U --user pip
  - pip install -U --user virtualenv
install:
  - export CC=mpicc
  - mkdir tmp
  - cd tmp
  - PETSC_CONFIGURE_OPTIONS="--download-hypre" ../scripts/firedrake-install --disable-ssh --minimal-petsc --adjoint --package_branch PyOP2 globals_matrices
  - . ./firedrake/bin/activate
  # Test that running firedrake-update works
  - firedrake-update
  # Having activated the virtualenv, attempt to save cached dependencies
  # This saves PETSc and petsc4py to speed up building
  - (cd firedrake; ../../scripts/firedrake-install --write-cache)
# command to run tests
script:
  - cd firedrake/src/firedrake
  - python setup.py build_ext --inplace
  - cd ..
  - pip install firedrake/
  - cd firedrake
  - make lint
  - (rc=0; for t in ${PYOP2_TESTS}; do py.test --short -v tests/${t} || rc=$?; done; exit $rc)
  - if [ -n $TEST_ADJOINT ]; then python ../dolfin-adjoint/tests_firedrake/test.py; fi
