image: quay.io/dolfinadjoint/dev-dolfin-adjoint

pipelines:
  default:
    - step:
        script:
          - export HOME=/home/fenics
          - export FENICS_PYTHON_MAJOR_VERSION=2
          - export FENICS_PYTHON_MINOR_VERSION=7
          - source /home/fenics/.profile
          - source /home/fenics/dolfin-adjoint.conf
          - update_libadjoint
          - update_dolfin-adjoint
          - py.test -v tests_dolfin/
